Feature/Photobook-Information
Team-Swamp/CaptureGraafsmeer pull request #54
Opened 2024-05-13 12:57 UTC by Wildeaso1

2024-05-13 13:01 UTC, bas-boop requested changes
Elke info field van dit allemaal is leeg. Dit is het engiste wat hoort gemaakt te zijn.

2024-05-14 08:16 UTC, Smokey1987 commented
Deze neem ik over vanwege een gebrek aan nieuwe art dat gemaakt moet worden

2024-05-14 09:38 UTC, bas-boop approved these changes
<img src="https://media.discordapp.net/attachments/887076306716610580/1227598123732308008/3dgifmaker93898.gif?ex=6628fcd8&is=661687d8&hm=1a6e0274224762790ceae99f8a80867258c73a90236321710c66c420411204a1&" alt="drawing" width="5000000"/>

2024-05-14 12:12 UTC, MartijnRene approved these changes
Double approve 👍

2024-05-14 12:12 UTC, merged